#!/usr/bin/env zsh

docker_cli_plugin_metadata() {
	local vendor="four43"
	local version="v1.0.0"
	local url="https://www.github.com/four43/dotfiles"
	local description="Kills all running containers"
	cat <<-EOF
	{"SchemaVersion":"0.1.0","Vendor":"${vendor}","Version":"${version}","ShortDescription":"${description}","URL":"${url}"}
EOF
}

version() {
	docker --version | cut -d " " -f 3 | cut -d "," -f 1
}

docker_killall() {
    echo "This will kill the following containers:"
    docker ps

    confirm-cmd docker ps --format='{{.ID}}' | xargs docker kill
}

case "$1" in
	docker-cli-plugin-metadata)
		docker_cli_plugin_metadata
		;;
	*)
		docker_killall
		;;
esac

