#!/bin/bash

# Outputs i3 config for setting up named workspaces based on our config vars:
# * I3_WS - list of our workspace names (space delimited string)
# * I3_WS_DISPLAYS - workspace display association (space delimited string, in the order of I3_WS)

# Space delimited string -> array
I3_WS=($(echo ${I3_WS}))
I3_WS_DISPLAYS=($(echo ${I3_WS_DISPLAYS}))

POLYBAR_WS="$(grep -E '^\s*ws-icon-[0-9]+' "$DOTFILE_DIR/themes/current/polybar/config" | awk -F ' = ' '{ print $2 }')"

# Set our $ws# vars
KEYBOARD_KEYS_WS=(1 2 3 4 5 6 7 8 9 0)
for ws_id in ${!KEYBOARD_KEYS_WS[@]}; do
    keyboard_key="${KEYBOARD_KEYS_WS[$ws_id]}"
    ws="${I3_WS[$ws_id]}"
    ws_display="${I3_WS_DISPLAYS[$ws_id]}"
    if [[ -z "${ws}" ]]; then
        # No workspace defined, just use default numbering
        echo "set \$ws${keyboard_key} \"${keyboard_key}\""
        echo "set \$ws_command${keyboard_key} \"i3-msg workspace ${keyboard_key}\""
        continue
    fi

    echo "set \$ws${keyboard_key} \"${keyboard_key}: ${ws}\""
    if [[ -n "${ws_display}" ]]; then
        echo "set \$ws_command${keyboard_key} \"i3-msg workspace ${ws} && i3-msg move workspace to output ${ws_display}\""
    else
        echo "set \$ws_command${keyboard_key} \"i3-msg workspace ${ws}\""
    fi
done

# Set our $ws_command# vars